version: '3.1'

services:

  dev:
    container_name: practical_test
    image: practical_test:1.0.0
    build:
      context: 
      dockerfile: ./Dockerfile
      command: npm run start:dev
    ports:
      - 3000:3000
      - 3001:9229
    networks: 
      - nestjs_networks
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - nesjs-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/